source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://git.baijiashilian.com/open-ios/specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HypnoNerd' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

pod 'Masonry', '~> 1.1.0'

pod 'AFNetworking', '~> 4.0.1'

pod 'SDWebImage', '~> 5.11.1'

pod 'MJRefresh', '~> 3.7.1'

pod 'BaijiaYun/BJVideoPlayerUI', '3.0.0-beta01'

  # Pods for HypnoNerd

  target 'HypnoNerdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HypnoNerdUITests' do
    # Pods for testing
  end

end
