source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HXSwiftStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit', '~> 5.0.1'

pod 'Moya', '~> 15.0.0-alpha.1'

pod 'PKHUD', '~> 5.0'

pod 'MJRefresh', '~> 3.7.1'

  # Pods for HXSwiftStudy

  target 'HXSwiftStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HXSwiftStudyUITests' do
    # Pods for testing
  end

end
